version: '3'

services:
  db:
    image: mysql:5
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: monikasiahaan067
      MYSQL_DATABASE: docker

  app:
    build: ./
    ports:
      - 8181:8080
    links:
      - db